### ISSUE TITLE
KPD-683 Hide the "expande drop-down-icon"

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#193]
**Userstory:** 
As a user, 
![image](https://user-images.githubusercontent.com/9428370/95656304-ca36c700-0b0d-11eb-9b4b-70c31fd8e777.png)

**Module name:**
https://github.com/vertelab/odoo-af/tree/Dev-12.0/calendar_af

**Branch name:** 
12.0-KPD-683-hide_expandable-drop-down.

**Description:** 
This fix hides the arrow-icon for the expandable dropdowns.

**Estimate:** 
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by AnilKesariya** [comment]
Estimated Hour 1 Hour

**Comment by FredrikArvas** [comment]
Please Go ahead! (it is also less then 2 hours, so you do not need to ask for permission).

**Comment by AnilKesariya** [comment]
Ok Got. thanks.

**Comment by AnilKesariya** [comment]
@FredrikArvas : There is an error on installation of calendar_af module with demo database.

Odoo Server Error
Traceback (most recent call last):
  File "/home/server/workspace/odoo/odoo12/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/server/workspace/odoo/odoo12/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/server/workspace/odoo/odoo12/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/home/server/workspace/odoo/odoo12/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/home/server/workspace/odoo/odoo12/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/server/workspace/odoo/odoo12/odoo/service/model.py", line 98, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/server/workspace/odoo/odoo12/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/server/workspace/odoo/odoo12/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/home/server/workspace/odoo/odoo12/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/home/server/workspace/odoo/odoo12/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/home/server/workspace/odoo/odoo12/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/server/workspace/odoo/odoo12/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/home/server/workspace/odoo/odoo12/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/home/server/workspace/odoo/odoo12/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/server/workspace/odoo/odoo12/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/home/server/workspace/odoo/odoo12/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/home/server/workspace/odoo/odoo12/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/server/workspace/odoo/odoo12/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/server/workspace/odoo/odoo12/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/server/workspace/odoo/odoo12/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/server/workspace/odoo/odoo12/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/server/workspace/odoo/odoo12/odoo/tools/convert.py", line 798, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/home/server/workspace/odoo/odoo12/odoo/tools/convert.py", line 845, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading calendar_af failed: file calendar_af/data/calendar.appointment.type.csv could not be processed:
 Unknown error during import: <class 'ValueError'>: Expected singleton: calendar.appointment.type(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13)
Unknown error during import: <class 'ValueError'>: Expected singleton: calendar.appointment.type(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14)
Unknown error during import: <class 'ValueError'>: Expected singleton: calendar.appointment.type(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15)
Unknown error during import: <class 'ValueError'>: Expected singleton: calendar.appointment.type(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
Unknown error during import: <class 'ValueError'>: Expected singleton: calendar.appointment.type(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17)
Unknown error during import: <class 'ValueError'>: Expected singleton: calendar.appointment.type(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18)
Unknown error during import: <class 'ValueError'>: Expected singleton: calendar.appointment.type(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19)
Unknown error during import: <class 'ValueError'>: Expected singleton: calendar.appointment.type(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)
Unknown error during import: <class 'ValueError'>: Expected singleton: calendar.appointment.type(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21)
Unknown error during import: <class 'ValueError'>: Expected singleton: calendar.appointment.type(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22)
Found more than 10 errors and more than one error per 10 records, interrupted to avoid showing too many errors.


----------------------
Do I need to fix this error? or should I try without demo database?

Regards,
Anil

**Comment by AnilKesariya** [comment]
I found that the csv demo data uses this module : **calendar_meeting_type** does not exist in any of our repository.

**Comment by FredrikArvas** [comment]
Please, explain a bit more. Are you missing a csv-file or do you want to disable it. 
I think that these meeting-types should be installed as data when we install the module calendar_af.

**Comment by AnilKesariya** [comment]
Assigned to @rupareliyahemangi145 As she has no error on installation she will update this issue.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

Created pull request for this iisue. https://github.com/vertelab/odoo-af/pull/213




Please check it and let me know if anything.

Thanks.

Best Regards,
Hemangi.

**Comment by rupareliyahemangi145** [comment]
Now can add screenshot.

![hide_expand](https://user-images.githubusercontent.com/36560391/95853835-a674ba80-0d73-11eb-8e1f-244be7129e88.png)

**Comment by FredrikArvas** [comment]
Hi @rupareliyahemangi145 
Please add your spent time at the "Actual Hours" in the description-box above.
thanks

**Comment by rupareliyahemangi145** [comment]
@FredrikArvas Added spent time of Anil and my.
