### ISSUE TITLE
[bug] AFC-1506 odoo-base/partner_test_data - does not install

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#448]
Maybe.... This module could be replaced by this: partner_test-data_fenix
(Then it should be depreciated).
1 This does not install:
https://github.com/vertelab/odoo-base/tree/Dev-12.0-Fenix-Sprint-02/partner_test_data

2
But this do install: partner_test-data_fenix
I cant find this module on github now.
But it was created from here: https://github.com/vertelab/odoo-af/issues/420
And moved with this: https://github.com/vertelab/odoo-base/pull/157

**Bugreport:** (only for Bug-Issues)
1 The module partner_test_data does not install
2 Please rename module to partner_test_data_**dafa**

**Full bugreport:** 
Fel:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3869, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3783, in _load_records_create
    return self.create(values)
  File "<decorator-gen-183>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 443, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 443, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/share/core-odoo/addons/digest/models/res_users.py", line 12, in create
    user = super(ResUsers, self).create(vals)
  File "<decorator-gen-181>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/share/core-odoo/addons/sales_team/models/res_users.py", line 17, in create
    user = super(ResUsers, self).create(vals)
  File "<decorator-gen-126>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/share/core-odoo/addons/auth_signup/models/res_users.py", line 216, in create
    user = super(ResUsers, self).create(values)
  File "<decorator-gen-125>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/share/odoo-web/web_dashboard_fenix/models/af_dashboard.py", line 61, in create
    res = super(ResUsers, self).create(vals)
  File "<decorator-gen-123>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/share/core-odoo/addons/mail/models/res_users.py", line 90, in create
    user = super(Users, self).create(values)
  File "<decorator-gen-106>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/usr/share/odooext-oca-server-auth/auth_saml_ol/models/res_users.py", line 107, in create
    result = super().create(vals_list)
  File "<decorator-gen-94>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 443, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 443, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/share/core-odoo/addons/base/models/res_users.py", line 1167, in create
    user = super(UsersView, self).create(values)
  File "<decorator-gen-92>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/usr/share/core-odoo/addons/base/models/res_users.py", line 955, in create
    return super(UsersImplied, self).create(vals_list)
  File "<decorator-gen-87>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/share/core-odoo/addons/base/models/res_users.py", line 471, in create
    users = super(Users, self.with_context(default_customer=False)).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3564, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3664, in _create
    cr.execute(query, params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "res_users_login_key"
DETAIL:  Key (login)=(ben.jackson@example.com) already exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/share/core-odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/share/core-odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/usr/share/core-odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/share/core-odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/share/core-odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 755, in parse
    self.parse(rec, mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3869, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3783, in _load_records_create
    return self.create(values)
  File "<decorator-gen-183>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 443, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 443, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/share/core-odoo/addons/digest/models/res_users.py", line 12, in create
    user = super(ResUsers, self).create(vals)
  File "<decorator-gen-181>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/share/core-odoo/addons/sales_team/models/res_users.py", line 17, in create
    user = super(ResUsers, self).create(vals)
  File "<decorator-gen-126>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/share/core-odoo/addons/auth_signup/models/res_users.py", line 216, in create
    user = super(ResUsers, self).create(values)
  File "<decorator-gen-125>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/share/odoo-web/web_dashboard_fenix/models/af_dashboard.py", line 61, in create
    res = super(ResUsers, self).create(vals)
  File "<decorator-gen-123>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 440, in _model_create_single
    return create(self, arg)
  File "/usr/share/core-odoo/addons/mail/models/res_users.py", line 90, in create
    user = super(Users, self).create(values)
  File "<decorator-gen-106>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/usr/share/odooext-oca-server-auth/auth_saml_ol/models/res_users.py", line 107, in create
    result = super().create(vals_list)
  File "<decorator-gen-94>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 443, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 443, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/usr/share/core-odoo/addons/base/models/res_users.py", line 1167, in create
    user = super(UsersView, self).create(values)
  File "<decorator-gen-92>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/usr/share/core-odoo/addons/base/models/res_users.py", line 955, in create
    return super(UsersImplied, self).create(vals_list)
  File "<decorator-gen-87>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/share/core-odoo/addons/base/models/res_users.py", line 471, in create
    users = super(Users, self.with_context(default_customer=False)).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3564, in create
    records = self._create(data_list)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3664, in _create
    cr.execute(query, params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "duplicate key value violates unique constraint "res_users_login_key"
DETAIL:  Key (login)=(ben.jackson@example.com) already exists.
" while parsing /usr/share/odoo-base/partner_test_data/data/res_user.xml:3, near
<record id="ben_jackson_user" model="res.users">
            <field name="name">Ben Jackson</field>
            <field name="login">ben.jackson@example.com</field>
            <field name="password"/>
            
            <field name="groups_id" eval="[(6,0,[ref('base.group_user')])]"/>
            <field name="partner_id" ref="partner_test_data.partner_ben"/>
            <field name="active" eval="True"/>
        </record>

**Module name:** (added by Nils or Fredrik)
odoo-base/partner_test_data
--

_ (name convention: [supplier-function]/[function-functionality-specialization] ) 

**Branch name:** 
Dev-12.0-[CRM/DAFA]-Sprint-[number]-AFC-1XXX-...

**Module type:** 
Application/Property/Resource/Glue/API module [see https://github.com/vertelab/odoo-af/issues/178 for more info]

**Integrations:**

**Test-steps:**

**Test-data:**

**Description to the manifest:** 
This module/update...

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours:

**Comment by iammiracle** [comment]
@FredrikArvas [Bug Fixed and Renamed](https://github.com/vertelab/odoo-base/pull/178)
