### ISSUE TITLE
BUG: AFC-1520 Can not install hr_holidays

### ISSUE THREAD

**Issue by FredrikArvas** [vertelab/odoo-af#457]
**Bugreport:** (only for Bug-Issues)
Steps to reproduce and where in the system the defect is located...

When installing hr_holidays I get the following error:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/share/core-odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/share/core-odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 759, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 746, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/usr/share/core-odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/share/core-odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/share/core-odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 195, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 299, in init_models
    model._auto_init()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2413, in _auto_init
    new = field.update_db(self, columns)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 2137, in update_db
    return super(Many2one, self).update_db(model, columns)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 901, in update_db
    self.update_db_notnull(model, column)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 941, in update_db_notnull
    model._init_column(self.name)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 2330, in _init_column
    value = field.default(self)
  File "/usr/share/core-odoo/addons/hr_holidays/models/hr_leave_allocation.py", line 35, in _default_holiday_status_id
    return self.env['hr.leave.type'].search(domain, limit=1)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1562, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/share/core-odoo/addons/hr_holidays/models/hr_leave_type.py", line 288, in _search
    leave_ids = super(HolidaysType, self)._search(args, offset=offset, limit=(None if post_sort else limit), order=order, count=count, access_rights_uid=access_rights_uid)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4126, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column hr_leave_type.active does not exist
LINE 1: ... "hr_leave_type".id FROM "hr_leave_type" WHERE ((("hr_leave_...
                                                             ^

**Estimate:** (@developers: Add your times here, not in comments please)
Estimated Hours: 
Estimated Date: 
Actual Hours: 20 Mins

**Comment by FredrikArvas** [comment]
hi @rupareliyahemangi145 
This might be a problem in our database too. If you can install it on your database, then leave it.

**Comment by rupareliyahemangi145** [comment]
Ok @FredrikArvas I will try to install it.

**Comment by rupareliyahemangi145** [comment]
Hello @FredrikArvas 

**hr_holidays** module is base module and I have installed it successfully in my database. It seems active field of **hr.leave.type** is removed from your database.

**Comment by FredrikArvas** [comment]
Ok, Thanks
